apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc.yaml
  - service.yaml
  - statefulset.yaml
images:
  - name: ethereum/go-client
    newTag: v1.13.13
  - name: gcr.io/prysmaticlabs/prysm/beacon-chain
    newTag: v4.2.1
