version: "3"

services:

  geth:
    image: ethereum/client-go
    restart: unless-stopped
    ports:
      - "30303:30303"
    volumes:
      - ${HOME}:/root
    expose:
      - "8545"
    networks: 
      - eth
    command:
      - --rpc
      - --rpcaddr
      - geth
      - --ipcdisable
      # see https://github.com/ethereum/wiki/issues/576
      - --rpcvhosts=*
  
  nginx:
    image: "nginx:alpine"
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/auth.txt:/etc/nginx/auth.txt:ro
      - ${PWD}/log:/var/log/nginx
    networks:
      - eth
    depends_on:
      - geth

networks:
  eth: