version: "3"

services:
  geth:
    image: ethereum/client-go
    restart: unless-stopped
    ports:
      - 8545:8545
      - 30303:30303
    volumes:
      - $PWD:/root
    command:
      - --rpc
      - --rpcaddr
      - 0.0.0.0
