version: "3"

services:
  geth:
    image: ethereum/client-go
    restart: unless-stopped
    ports:
      - "8545"
      - "30303:30303"
      - "30303:30303/udp"
    volumes:
      - $PWD:/root
    networks: 
      - eth
    command:
      - --rpc
      - --rpcaddr
      - 0.0.0.0
      - --ipcdisable
  
  nginx:
    build: .
    ports:
      - "1020:80"
    volumes:
      - $PWD/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/auth:/etc/nginx/auth
      - $PWD/log:/var/log/nginx
    networks:
      - eth

networks:
  eth: