apiVersion: v1
kind: Namespace
metadata:
  name: blockchain-node

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: geth-node
  namespace: blockchain-node
spec:
  selector:
    matchLabels:
      app: geth-node
  replicas: 1
  serviceName: gethrpc
  template:
    metadata:
      labels:
        app: geth-node
    spec:
      terminationGracePeriodSeconds: 120
      containers:
        - name: geth
          image: ethereum/client-go:v1.9.21
          ports:
            - containerPort: 8545
            - containerPort: 8546
            - { containerPort: 30303, protocol: TCP }
            - { containerPort: 30303, protocol: UDP }
          args: [
              "--nousb",
              "--dev", # CHANGE HERE!
              "--ipcpath=/ipc/geth.jsonrpc",
              "--datadir=/chaindata",
              "--http",
              "--http.addr=0.0.0.0",
              "--http.api=eth,net,web3",
              "--http.vhosts=*",
              "--http.corsdomain=*",
              "--ws",
              "--ws.addr=0.0.0.0",
              "--ws.api=eth,net,web3",
              "--ws.origins=*",
              "--graphql",
              "--graphql.corsdomain=*",
              "--graphql.vhosts=*",
            ]
          volumeMounts:
            - name: chaindata
              mountPath: /chaindata
            - name: ipc
              mountPath: /ipc
      volumes:
        - name: ipc
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: "chaindata"
      spec:
        storageClassName: standard # CHANGE HERE!
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi # CHANGE HERE!

---
apiVersion: v1
kind: Service
metadata:
  name: gethrpc
  namespace: blockchain-node
spec:
  ports:
    - protocol: TCP
      targetPort: 8545
      port: 8545
      name: http
    - protocol: TCP
      targetPort: 8546
      port: 8546
      name: websoket
  clusterIP: None
  selector:
    app: geth-node
