apiVersion: v1
kind: Namespace
metadata:
  name: blockchain

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gethnode
  namespace: blockchain
spec:
  selector:
    matchLabels:
      app: gethnode
  replicas: 1
  serviceName: gethnode
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gethnode
    spec:
      terminationGracePeriodSeconds: 300
      containers:
        - name: geth
          image: docker.io/ethereum/client-go:v1.10.8
          ports:
            - containerPort: 8545
            - containerPort: 8546
            - { containerPort: 30303, protocol: TCP }
            - { containerPort: 30303, protocol: UDP }
          args:
            [
              "--ipcdisable",
              "--datadir=/chaindata",
              "--http",
              "--http.addr=0.0.0.0",
              "--http.api=eth,net,web3",
              "--http.vhosts=*",
              "--http.corsdomain=*",
              "--ws",
              "--ws.addr=0.0.0.0",
              "--ws.api=eth,net,web3",
              "--ws.origins=*",
            ]
          resources:
            requests:
              memory: 2G
              cpu: 1000m
            limits:
              memory: 16G
              cpu: 8000m
          livenessProbe:
            initialDelaySeconds: 10
            timeoutSeconds: 10
            httpGet:
              path: /
              port: 8545
          readinessProbe:
            httpGet:
              path: /
              port: 8545
          volumeMounts:
            - name: chaindata
              mountPath: /chaindata
  volumeClaimTemplates:
    - metadata:
        name: "chaindata"
      spec:
        storageClassName: CHANGE_TO_YOUR_STORAGE_CLASS
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 750Gi

---
apiVersion: v1
kind: Service
metadata:
  name: gethnode
  namespace: blockchain
spec:
  ports:
    - protocol: TCP
      targetPort: 8545
      port: 8545
      name: http
    - protocol: TCP
      targetPort: 8546
      port: 8546
      name: websoket
  clusterIP: None
  selector:
    app: gethnode
