version: "3.8"

services:
  geth:
    image: ethereum/client-go:v1.14.7
    restart: unless-stopped
    ports:
      - 30303:30303
      - 30303:30303/udp
      - 8545:8545
      - 8546:8546
    volumes:
      - ${GETH_DATADIR:-/root/.ethereum}:/root/.ethereum
    stop_signal: SIGINT
    stop_grace_period: 2m
    healthcheck:
      test: ["CMD-SHELL", "geth attach --exec eth.blockNumber"]
      interval: 10s
      timeout: 5s
      retries: 5
    command:
      - --http
      - --http.api=eth,net,engine,admin,web3
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --ws
      - --ws.origins=*
      - --ws.addr=0.0.0.0
      - --ws.api=eth,net,web3
      - --graphql
      - --graphql.corsdomain=*
      - --graphql.vhosts=*
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
  prysm:
    image: prysmaticlabs/prysm-beacon-chain:v5.0.4
    restart: unless-stopped
    stop_grace_period: 2m
    volumes:
      - ${PRYSM_DATADIR:-/root/.eth2}:/data
      - ${GETH_DATADIR:-/root/.ethereum}:/geth
    depends_on:
      geth:
        condition: service_healthy
    ports:
      - 4000:4000
      - 3500:3500
    command:
      - --accept-terms-of-use
      - --datadir=/data
      - --execution-endpoint=/geth/geth.ipc
      - --rpc-host=0.0.0.0
      - --rpc-port=4000
      - --grpc-gateway-corsdomain=*
      - --grpc-gateway-host=0.0.0.0
      - --grpc-gateway-port=3500
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"