apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chainrpc
resources:
  - pvc.yaml
  - service.yaml
  - geth.yaml
  - prysm.yaml
configMapGenerator:
  - name: geth-jwt
    files: ["jwt.hex"]
    options:
      disableNameSuffixHash: true
images:
  - name: ghcr.io/islishude/geth
    newTag: 1.13.3
  - name: gcr.io/prysmaticlabs/prysm/beacon-chain
    newTag: v4.0.8
