apiVersion: v1
kind: Service
metadata:
  name: gethrpc
spec:
  type: NodePort
  ports:
    - protocol: TCP
      targetPort: 8545
      port: 8545
      nodePort: 31000
      name: http
    - protocol: TCP
      targetPort: 8546
      port: 8546
      nodePort: 31002
      name: websoket
  selector:
    app: geth-node
