apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: geth
spec:
  selector:
    matchLabels:
      app: geth-node
  replicas: 2
  serviceName: gethrpc
  template:
    metadata:
      label:
        app: geth-node
    spec:
      containers:
        - name: geth
          image: ethereum/client-go:v1.9.17
          resources:
            limits: { cpu: "8000m", memory: "16G" }
            requests: { cpu: "8000m", memory: "16G" }
          ports:
            - containerPort: 8545
            - containerPort: 8546
            - containerPort: 8547
            - { containerPort: 30303, protocol: TCP }
            - { containerPort: 30303, protocol: UDP }
          args:
            [
              "--http",
              "--http.api=eth,txpool,net,web3",
              "--http.vhosts=*",
              "--http.corsdomain=*",
              "--ws",
              "--ws.addr=0.0.0.0",
              "--ws.origin=*",
              "--ws.api=eth,net,web3,txpool",
              "--graphql",
              "--graphql.addr=0.0.0.0",
              "--graphql.corsdomain=*",
              "--graphql.vhosts=*",
              "--datadir=/chaindata",
            ]
          volumeMounts:
            - name: chaindata
              mountPath: /chaindata
      volumeClaimTemplates:
        - metadata:
            name: chaindata
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: YOUR_STORAGE_CLASS_NAME
            resources:
              requests:
                storage: 500Gi
