apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: geth
spec:
  selector:
    matchLabels:
      app: geth-node
  replicas: 1
  serviceName: gethrpc
  template:
    metadata:
      labels:
        app: geth-node
    spec:
      terminationGracePeriodSeconds: 120
      containers:
        - name: geth
          image: ethereum/client-go:v1.9.20
          ports:
            - containerPort: 8545
            - containerPort: 8546
            - { containerPort: 30303, protocol: TCP }
            - { containerPort: 30303, protocol: UDP }
          args: [
              "--nousb",
              # "--dev",
              "--ipcpath=/ipc/geth.jsonrpc",
              "--datadir=/chaindata",
              "--http",
              "--http.addr=0.0.0.0",
              "--http.api=eth,net,web3",
              "--http.vhosts=*",
              "--http.corsdomain=*",
              "--ws",
              "--ws.addr=0.0.0.0",
              "--ws.api=eth,net,web3",
              "--ws.origins=*",
              "--graphql",
              "--graphql.corsdomain=*",
              "--graphql.vhosts=*",
            ]
          volumeMounts:
            - name: chaindata
              mountPath: /chaindata
            - name: ipc
              mountPath: /ipc
      volumes:
        - name: ipc
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: "chaindata"
      spec:
        storageClassName: standard # CHANGE HERE!
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi # CHANGE HERE!
