version: "3"

services:
  geth:
    image: "ethereum/client-go:v1.8.17"
    restart: unless-stopped
    ports:
      - "30303:30303"
      - "30303:30303/udp"
    volumes:
      - ${PWD}/.ethereum:/root/.ethereum
    expose:
      - "8545"
    networks: 
      - eth
    stop_signal: SIGINT
    stop_grace_period: 1m30s
    command:
      - --rpc
      - --rpcapi="eth,txpool,net,web3"
      - --rpcaddr=geth
      - --rpcvhosts=*
      # Maximum number of non-executable transaction slots for all accounts (default: 4096)
      - --txpool.globalslot=20000
      # Maximum amount of time executable transaction are queued (default: 3h0m0s)
      - --txpool.lifetime=1h0m0s
      # Megabytes of memory allocated to internal caching (default: 1024)
      - --cache=4096
      # Maximum number of network peers (network disabled if set to 0) (default: 25)
      - --maxpeers=100
      # Blockchain sync mode ("fast", "full", or "light")
      - --syncmode=full
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  nginx:
    image: "nginx:1.14.0"
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/auth.txt:/etc/nginx/auth.txt:ro
      - ${PWD}/log:/var/log/nginx
    networks:
      - eth
    depends_on:
      - geth

networks:
  eth:
