version: "3"

services:
    parity:
        image: parity/parity:v2.5.13
        ports:
            - "30303:30303"
            - "30303:30303/udp"
            - "8545:8545"
            - "8546:8546"
        volumes:
            - /chaindata:/chaindata
        stop_signal: SIGINT
        stop_grace_period: 2m
        command:
            - --no-secretstore
            - --base-path=/chaindata
            - --no-download
            - --no-config
            - --auto-update=none
            - --tracing=on
            - --jsonrpc-interface=all
            - --jsonrpc-apis=safe
            - --jsonrpc-hosts=all
            - --ws-interface=all
            - --ws-apis=safe
            - --ws-origins=all
            - --ws-hosts=all
        logging:
            driver: "json-file"
            options:
                max-size: "2m"
                max-file: "10"
