version: "3.8"

services:
  parity:
    image: openethereum/openethereum:v3.3.0-rc.8
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
      - "8546:8546"
    volumes:
      - /data/chaindata:/chaindata
    user: root
    stop_grace_period: 2m
    restart: unless-stopped
    command:
      - --no-ipc
      - --no-secretstore
      - --no-config
      - --no-warp
      - --base-path=/chaindata
      - --tracing=on
      - --jsonrpc-interface=all
      - --jsonrpc-apis=safe
      - --jsonrpc-hosts=all
      - --jsonrpc-cors=all
      - --ws-interface=all
      - --ws-origins=all
      - --ws-hosts=all
      - --min-peers=25
      - --max-peers=100
      - --tx-queue-no-early-reject
      - --tx-queue-size=512
      - --cache-size=20480
      - --pruning-history=1024
      - --can-restart
      - --ws-max-payload=30
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"
