apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chaindata-geth
spec:
  storageClassName: default # change it!
  resources:
    requests:
      storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chaindata-prysm
spec:
  storageClassName: default # change it!
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
