version: "3"

services:
  geth:
    build: .
    restart: unless-stopped
    ports:
      - "8545:8545"
      - "8546:8546"
    volumes:
      - ${PWD}/.ethereum/:/geth/.ethereum/
    stop_signal: SIGINT
    stop_grace_period: 2m
    command:
      - --rpc
      - --rpcaddr=0.0.0.0
      - --rpcvhosts=*
      - --rpccorsdomain=*
      - --ws
      - --wsorigins=*
      - --nodiscover
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
