name: ci

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  pull_request:
    branches:
      - "main"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: islishude/geth

jobs:
  main:
    concurrency: "build"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Login to Github Registry
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: docker-meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch

      - name: Build
        uses: docker/build-push-action@v5
        with:
          push: true
          pull: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}
          annotations: ${{ steps.docker-meta.outputs.annotations }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: latest

      - name: Docker meta for debug target
        id: docker-meta-debug
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}},suffix=debug
            type=ref,event=branch,suffix=debug

      - name: Build debug
        uses: docker/build-push-action@v5
        with:
          push: true
          pull: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.docker-meta-debug.outputs.tags }}
          labels: ${{ steps.docker-meta-debug.outputs.labels }}
          annotations: ${{ steps.docker-meta-debug.outputs.annotations }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: debug
